2021-10-16 06:04:04,957 (62612/MainThread) litecli.main ERROR - sql: 'select * from disease_site;', error: OperationalError('no such table: disease_site')
2021-10-16 06:04:04,958 (62612/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: no such table: disease_site\n'
2021-10-16 06:04:12,134 (62612/MainThread) litecli.main ERROR - sql: '.q', error: OperationalError('near ".": syntax error')
2021-10-16 06:04:12,134 (62612/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-16 06:04:13,285 (62612/MainThread) litecli.main ERROR - sql: '.q', error: OperationalError('near ".": syntax error')
2021-10-16 06:04:13,285 (62612/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-16 06:13:22,684 (63737/MainThread) litecli.main ERROR - sql: '.e', error: OperationalError('near ".": syntax error')
2021-10-16 06:13:22,687 (63737/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-16 06:14:09,895 (63951/MainThread) litecli.main ERROR - sql: 'commit;', error: OperationalError('cannot commit - no transaction is active')
2021-10-16 06:14:09,897 (63951/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: cannot commit - no transaction is active\n'
2021-10-16 06:14:38,609 (63951/MainThread) litecli.main ERROR - sql: '.q', error: OperationalError('near ".": syntax error')
2021-10-16 06:14:38,610 (63951/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-16 06:20:52,891 (64969/MainThread) litecli.main ERROR - sql: '.q', error: OperationalError('near ".": syntax error')
2021-10-16 06:20:52,893 (64969/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-16 06:20:54,316 (64969/MainThread) litecli.main ERROR - sql: '.e', error: OperationalError('near ".": syntax error')
2021-10-16 06:20:54,316 (64969/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-16 09:30:49,761 (73025/MainThread) litecli.main ERROR - sql: 'select * from disease_site;', error: OperationalError('no such table: disease_site')
2021-10-16 09:30:49,763 (73025/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: no such table: disease_site\n'
2021-10-16 09:31:02,841 (73025/MainThread) litecli.main ERROR - sql: '.q', error: OperationalError('near ".": syntax error')
2021-10-16 09:31:02,842 (73025/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-16 09:31:43,076 (73101/MainThread) litecli.main ERROR - sql: '.q', error: OperationalError('near ".": syntax error')
2021-10-16 09:31:43,078 (73101/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-17 10:48:32,987 (78999/MainThread) litecli.main ERROR - sql: '.e', error: OperationalError('near ".": syntax error')
2021-10-17 10:48:32,990 (78999/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-17 10:48:35,466 (78999/MainThread) litecli.main ERROR - sql: '.exit\\', error: OperationalError('near ".": syntax error')
2021-10-17 10:48:35,467 (78999/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-17 10:48:38,126 (78999/MainThread) litecli.main ERROR - sql: '.qu', error: OperationalError('near ".": syntax error')
2021-10-17 10:48:38,126 (78999/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-17 17:14:56,129 (94722/MainThread) litecli.main ERROR - sql: '.q', error: OperationalError('near ".": syntax error')
2021-10-17 17:14:56,132 (94722/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-22 19:52:50,888 (27108/MainThread) litecli.main ERROR - sql: 'describe', error: ArgumentMissing('Table name required.')
2021-10-22 19:52:50,891 (27108/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 121, in execute\n    return special_cmd.handler(cur=cur, arg=arg, verbose=verbose)\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/dbcommands.py", line 191, in describe\n    raise ArgumentMissing("Table name required.")\nlitecli.packages.special.main.ArgumentMissing: Table name required.\n'
2021-10-22 20:16:06,469 (27108/MainThread) litecli.main ERROR - sql: '.q', error: OperationalError('near ".": syntax error')
2021-10-22 20:16:06,470 (27108/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2021-10-22 20:59:03,976 (35944/MainThread) litecli.main ERROR - sql: '.q', error: OperationalError('Not connected to database.')
2021-10-22 20:59:03,978 (35944/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 115, in run\n    raise OperationalError("Not connected to database.")\nsqlite3.OperationalError: Not connected to database.\n'
2021-10-22 20:59:04,984 (35944/MainThread) litecli.main ERROR - sql: '.e', error: OperationalError('Not connected to database.')
2021-10-22 20:59:04,985 (35944/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 115, in run\n    raise OperationalError("Not connected to database.")\nsqlite3.OperationalError: Not connected to database.\n'
2021-10-22 20:59:06,806 (35944/MainThread) litecli.main ERROR - sql: '.exit', error: OperationalError('Not connected to database.')
2021-10-22 20:59:06,807 (35944/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 115, in run\n    raise OperationalError("Not connected to database.")\nsqlite3.OperationalError: Not connected to database.\n'
2021-10-22 20:59:08,486 (35944/MainThread) litecli.main ERROR - sql: '.quit', error: OperationalError('Not connected to database.')
2021-10-22 20:59:08,486 (35944/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 115, in run\n    raise OperationalError("Not connected to database.")\nsqlite3.OperationalError: Not connected to database.\n'
2021-12-31 08:30:47,268 (84000/MainThread) litecli.main ERROR - sql: '\\#q', error: OperationalError('unrecognized token: "\\"')
2021-12-31 08:30:47,271 (84000/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: unrecognized token: "\\"\n'
2022-01-01 07:46:39,783 (13816/MainThread) litecli.main ERROR - sql: '.q', error: OperationalError('near ".": syntax error')
2022-01-01 07:46:39,785 (13816/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2022-01-01 07:54:20,122 (15050/MainThread) litecli.main ERROR - sql: '.q', error: OperationalError('near ".": syntax error')
2022-01-01 07:54:20,124 (15050/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/src/ro-resident-tool/resident_app/.env/lib/python3.9/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2022-03-30 07:45:40,071 (15031/MainThread) litecli.main ERROR - sql: '.q', error: OperationalError('near ".": syntax error')
2022-03-30 07:45:40,074 (15031/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/.pyenv/versions/3.10.2/lib/python3.10/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/.pyenv/versions/3.10.2/lib/python3.10/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/.pyenv/versions/3.10.2/lib/python3.10/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/.pyenv/versions/3.10.2/lib/python3.10/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ".": syntax error\n'
2022-04-16 10:52:53,698 (17191/MainThread) litecli.main ERROR - sql: 'create table phrase (', error: OperationalError('incomplete input')
2022-04-16 10:52:53,699 (17191/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/.pyenv/versions/3.10.2/lib/python3.10/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/.pyenv/versions/3.10.2/lib/python3.10/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/.pyenv/versions/3.10.2/lib/python3.10/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/.pyenv/versions/3.10.2/lib/python3.10/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: incomplete input\n'
2022-04-16 10:54:31,370 (17191/MainThread) litecli.main ERROR - sql: 'create table phrase (\n  id integer not null autoincrement,\n  abbr text unique not null,\n  phrase text not null );', error: OperationalError('near "autoincrement": syntax error')
2022-04-16 10:54:31,370 (17191/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/dmr/.pyenv/versions/3.10.2/lib/python3.10/site-packages/litecli/sqlexecute.py", line 122, in run\n    for result in special.execute(cur, sql):\n  File "/Users/dmr/.pyenv/versions/3.10.2/lib/python3.10/site-packages/litecli/packages/special/main.py", line 109, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/dmr/.pyenv/versions/3.10.2/lib/python3.10/site-packages/litecli/main.py", line 441, in one_iteration\n    for title, cur, headers, status in res:\n  File "/Users/dmr/.pyenv/versions/3.10.2/lib/python3.10/site-packages/litecli/sqlexecute.py", line 126, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "autoincrement": syntax error\n'
